assign:
<<<<<<< HEAD
<<<<<<< HEAD
  issues: enabled
  pull_requests: disabled
=======
  issues: enable
  pull_requests: disable
>>>>>>> 4a86bdf0 ([Enhance] Add openmmlab-bot configuration for automatic issue assigning (#1736))
=======
  issues: enabled
  pull_requests: disabled
>>>>>>> dae131ea (Update .owners.yml (#1754))
  strategy:
    # random
    daily-shift-based
  scedule:
    '*/1 * * * *'
  assignees:
<<<<<<< HEAD
    - Tau-J
    - LareinaM
    - Ben-Louis
    - LareinaM
    - Ben-Louis
    - Tau-J
    - Tau-J
=======
    - ly015
    - Tau-J
    - Ben-Louis
    - Tau-J
<<<<<<< HEAD
<<<<<<< HEAD
>>>>>>> 4a86bdf0 ([Enhance] Add openmmlab-bot configuration for automatic issue assigning (#1736))
=======
=======
    - Ben-Louis
>>>>>>> 4c397f2d (Update .owners.yml (#1933))
    - ly015
    - ly015
>>>>>>> 8c58a18b (Update .owners.yml (#1762))
